### ISSUE TITLE
To-do Next

### ISSUE THREAD

**Issue by KBuild** [KBuild/oauthorize#1]
- [ ] migrate to ES6 
- [ ] example for express4
- [ ] refactor some code
- [ ] make new test case
